version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "<< Your S3 bucket name >>"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
        - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
        - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
        - echo Build started 
#         - ng build
        - sonar-scanner
            -Dsonar.login=sqp_f29b48acfd902e30987476ffc3e39cb5282d5c71
            -Dsonar.host.url=http://65.0.129.38:9000/
            -Dsonar.projectKey=Test_Project
# artifacts:
#     files:
#         - '**/*'
#     base-directory: 'dist*'
#     discard-paths: yes
